# Generated by Django 5.2 on 2026-03-15 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_id', models.PositiveSmallIntegerField(default=0)),
                ('charging_profile_id', models.PositiveIntegerField()),
                ('stack_level', models.PositiveSmallIntegerField(default=0)),
                ('profile_purpose', models.CharField(choices=[('ChargePointMaxProfile', 'Charge Point Max Profile'), ('TxDefaultProfile', 'TX Default Profile'), ('TxProfile', 'TX Profile')], max_length=30)),
                ('profile_kind', models.CharField(choices=[('Absolute', 'Absolute'), ('Recurring', 'Recurring'), ('Relative', 'Relative')], max_length=20)),
                ('recurrency_kind', models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=10)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charging_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_profiles', to='stations.chargingstation')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charging_profiles', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Charging Profile',
                'verbose_name_plural': 'Charging Profiles',
                'db_table': 'cp_charging_profile',
                'unique_together': {('charging_station', 'connector_id', 'stack_level', 'profile_purpose')},
            },
        ),
        migrations.CreateModel(
            name='ChargingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('start_schedule', models.DateTimeField(blank=True, null=True)),
                ('charging_rate_unit', models.CharField(choices=[('A', 'Amperes'), ('W', 'Watts')], max_length=2)),
                ('min_charging_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('schedule_periods', models.JSONField(default=list)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='smart_charging.chargingprofile')),
            ],
            options={
                'verbose_name': 'Charging Schedule',
                'verbose_name_plural': 'Charging Schedules',
                'db_table': 'cp_charging_schedule',
            },
        ),
    ]
