# Generated by Django 5.2 on 2026-03-15 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired'), ('Used', 'Used'), ('Failed', 'Failed')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charging_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='stations.chargingstation')),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='stations.connector')),
                ('id_token', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='authorization.idtoken')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'cp_reservation',
                'ordering': ['-created_at'],
            },
        ),
    ]
