# Generated by Django 5.2 on 2026-03-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='cp_payment__user_id_b65927_idx',
            old_name='cp_payment_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='paymenttransaction',
            new_name='cp_payment__status_b04301_idx',
            old_name='cp_payment_status_created_idx',
        ),
    ]
