# Generated by Django 5.2 on 2026-03-15 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('meter_start', models.BigIntegerField(default=0)),
                ('meter_stop', models.BigIntegerField(blank=True, null=True)),
                ('energy_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stop_reason', models.CharField(blank=True, choices=[('DeAuthorized', 'De-Authorized'), ('EmergencyStop', 'Emergency Stop'), ('EVDisconnected', 'EV Disconnected'), ('HardReset', 'Hard Reset'), ('Local', 'Local'), ('Other', 'Other'), ('PowerLoss', 'Power Loss'), ('Reboot', 'Reboot'), ('Remote', 'Remote'), ('SoftReset', 'Soft Reset'), ('UnlockCommand', 'Unlock Command')], max_length=30)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charging_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='stations.chargingstation')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='stations.connector')),
                ('id_token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='authorization.idtoken')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'cp_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('measurand', models.CharField(choices=[('Energy.Active.Import.Register', 'Energy Active Import Register'), ('Power.Active.Import', 'Power Active Import'), ('Current.Import', 'Current Import'), ('Voltage', 'Voltage'), ('SoC', 'State of Charge'), ('Temperature', 'Temperature'), ('Frequency', 'Frequency')], default='Energy.Active.Import.Register', max_length=50)),
                ('phase', models.CharField(blank=True, max_length=10)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit', models.CharField(choices=[('Wh', 'Wh'), ('kWh', 'kWh'), ('W', 'W'), ('kW', 'kW'), ('A', 'A'), ('V', 'V'), ('Percent', 'Percent'), ('Celsius', 'Celsius')], default='Wh', max_length=10)),
                ('context', models.CharField(blank=True, max_length=30)),
                ('location', models.CharField(blank=True, max_length=20)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_values', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Meter Value',
                'verbose_name_plural': 'Meter Values',
                'db_table': 'cp_meter_value',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['charging_station', 'state'], name='cp_transact_chargin_e30911_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['id_token', '-time_start'], name='cp_transact_id_toke_db3ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='metervalue',
            index=models.Index(fields=['transaction', 'measurand', 'timestamp'], name='cp_meter_va_transac_5e857b_idx'),
        ),
    ]
