# Generated by Django 5.2 on 2026-03-15 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAuthList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_token', models.CharField(max_length=36)),
                ('id_tag_info', models.JSONField()),
                ('list_version', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Local Auth List Entry',
                'verbose_name_plural': 'Local Auth List Entries',
                'db_table': 'cp_local_auth_list',
            },
        ),
        migrations.CreateModel(
            name='AuthorizationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_id', models.PositiveSmallIntegerField()),
                ('id_token', models.CharField(max_length=36)),
                ('status', models.CharField(max_length=20)),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('charging_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stations.chargingstation')),
            ],
            options={
                'verbose_name': 'Authorization Record',
                'verbose_name_plural': 'Authorization Records',
                'db_table': 'cp_authorization_record',
                'ordering': ['-authorized_at'],
            },
        ),
        migrations.CreateModel(
            name='IdToken',
            fields=[
                ('id_token', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('token_type', models.CharField(choices=[('RFID', 'RFID Card'), ('APP', 'Mobile App Token'), ('ROAMING', 'Roaming Card')], default='RFID', max_length=10)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Blocked', 'Blocked'), ('Expired', 'Expired'), ('Invalid', 'Invalid'), ('ConcurrentTx', 'Concurrent Transaction')], default='Invalid', max_length=20)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('parent_id_token', models.CharField(blank=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.operator')),
            ],
            options={
                'verbose_name': 'ID Token',
                'verbose_name_plural': 'ID Tokens',
                'db_table': 'cp_id_token',
            },
        ),
    ]
