# Generated by Django 5.2 on 2026-03-15 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idtoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localauthlist',
            name='charging_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_auth_list', to='stations.chargingstation'),
        ),
        migrations.AlterUniqueTogether(
            name='localauthlist',
            unique_together={('charging_station', 'id_token')},
        ),
    ]
