# Generated by Django 5.2 on 2026-03-15 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsmsVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('int', 'Integer'), ('float', 'Float'), ('str', 'String'), ('bool', 'Boolean'), ('json', 'JSON')], default='str', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_per_station', models.BooleanField(default=False, help_text='Whether this variable can be overridden per charging station via StationVariable')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'CSMS Variable',
                'verbose_name_plural': 'CSMS Variables',
                'db_table': 'cp_csms_variable',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='StationVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charging_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_variables', to='stations.chargingstation')),
                ('csms_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_overrides', to='config.csmsvariable')),
            ],
            options={
                'verbose_name': 'Station Variable',
                'verbose_name_plural': 'Station Variables',
                'db_table': 'cp_station_variable',
                'unique_together': {('charging_station', 'csms_variable')},
            },
        ),
    ]
