# Generated by Django 5.2 on 2026-03-15 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSession',
            fields=[
                ('session_id', models.CharField(max_length=80, primary_key=True, serialize=False, unique=True)),
                ('connector_id', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=10)),
                ('fail_reason', models.CharField(blank=True, max_length=200)),
                ('kwh_current', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('final_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('final_cost', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charging_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_sessions', to='stations.chargingstation')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_session', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'App Session',
                'verbose_name_plural': 'App Sessions',
                'db_table': 'cp_app_session',
                'ordering': ['-created_at'],
            },
        ),
    ]
