# Generated by Django 5.2 on 2026-03-15 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobile_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='appsession',
            index=models.Index(fields=['user', '-created_at'], name='cp_app_sess_user_id_d6ecd1_idx'),
        ),
        migrations.AddIndex(
            model_name='appsession',
            index=models.Index(fields=['charging_station', 'status'], name='cp_app_sess_chargin_6b5760_idx'),
        ),
    ]
