# Generated by Django 5.2 on 2026-03-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(db_index=True, max_length=50)),
                ('msg_id', models.CharField(max_length=36)),
                ('direction', models.SmallIntegerField(choices=[(2, 'CP → CSMS'), (3, 'CSMS → CP'), (4, 'Error')])),
                ('action', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'OCPP Message',
                'verbose_name_plural': 'OCPP Messages',
                'db_table': 'cp_ocpp_message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['station_id', '-created_at'], name='cp_ocpp_mes_station_621734_idx'), models.Index(fields=['action', '-created_at'], name='cp_ocpp_mes_action_6f6373_idx')],
            },
        ),
    ]
