# Generated by Django 5.2 on 2026-03-15 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50, unique=True)),
                ('vendor_name', models.CharField(blank=True, max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=50)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('iccid', models.CharField(blank=True, max_length=50)),
                ('imsi', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable'), ('Faulted', 'Faulted'), ('Offline', 'Offline')], default='Offline', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('last_boot_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Charging Station',
                'verbose_name_plural': 'Charging Stations',
                'db_table': 'cp_charging_station',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Operator',
                'verbose_name_plural': 'Operators',
                'db_table': 'cp_operator',
            },
        ),
        migrations.CreateModel(
            name='EVSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evse_id', models.PositiveSmallIntegerField()),
                ('charging_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evses', to='stations.chargingstation')),
            ],
            options={
                'verbose_name': 'EVSE',
                'verbose_name_plural': 'EVSEs',
                'db_table': 'cp_evse',
                'unique_together': {('charging_station', 'evse_id')},
            },
        ),
        migrations.CreateModel(
            name='FirmwareHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmware_url', models.URLField(max_length=512)),
                ('retrieve_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Downloaded', 'Downloaded'), ('DownloadFailed', 'Download Failed'), ('Downloading', 'Downloading'), ('Idle', 'Idle'), ('InstallationFailed', 'Installation Failed'), ('Installing', 'Installing'), ('Installed', 'Installed')], default='Idle', max_length=30)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('charging_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmware_history', to='stations.chargingstation')),
            ],
            options={
                'verbose_name': 'Firmware History',
                'verbose_name_plural': 'Firmware Histories',
                'db_table': 'cp_firmware_history',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='stations.operator'),
        ),
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.TextField(blank=True)),
                ('is_readonly', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charging_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='stations.chargingstation')),
            ],
            options={
                'verbose_name': 'Device Configuration',
                'verbose_name_plural': 'Device Configurations',
                'db_table': 'cp_device_configuration',
                'unique_together': {('charging_station', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_id', models.PositiveSmallIntegerField()),
                ('connector_type', models.CharField(choices=[('Type1', 'Type 1 (SAE J1772)'), ('Type2', 'Type 2 (IEC 62196)'), ('CHAdeMO', 'CHAdeMO'), ('CCS1', 'CCS1'), ('CCS2', 'CCS2'), ('Schuko', 'Schuko'), ('Other', 'Other')], default='Type2', max_length=20)),
                ('max_power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('current_status', models.CharField(choices=[('Available', 'Available'), ('Preparing', 'Preparing'), ('Charging', 'Charging'), ('SuspendedEVSE', 'Suspended EVSE'), ('SuspendedEV', 'Suspended EV'), ('Finishing', 'Finishing'), ('Reserved', 'Reserved'), ('Unavailable', 'Unavailable'), ('Faulted', 'Faulted')], default='Unavailable', max_length=20)),
                ('status_updated_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('info', models.CharField(blank=True, max_length=50)),
                ('vendor_id', models.CharField(blank=True, max_length=255)),
                ('vendor_error_code', models.CharField(blank=True, max_length=50)),
                ('evse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='stations.evse')),
            ],
            options={
                'verbose_name': 'Connector',
                'verbose_name_plural': 'Connectors',
                'db_table': 'cp_connector',
                'unique_together': {('evse', 'connector_id')},
            },
        ),
    ]
